### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'prototype' of undefined(…)

### ISSUE THREAD

**Issue by maxkfranz** [cytoscape/cytoscape.js-spread#1]
From https://github.com/cytoscape/cytoscape.js/issues/1147
## 

Firstly its an awesome layout extension....it works so perfectly on my local .....

but when I access it with my minified code (not the minified spread layout / cytoscape). It gives me the below error.

Uncaught (in promise) TypeError: Cannot read property 'prototype' of undefined(…)
protoreq @ cytoscape.js:7070
fnAsRequire @ cytoscape.js:7121
(anonymous function) @ cytoscape.js:7195
$$.Promise.then._p.running @ cytoscape.js:7194
$$.fn.thread.run @ cytoscape.js:7185
SpreadLayout.run @ layout.js:266
$$.fn.core.layout @ cytoscape.js:8667
callback @ cytoscape.js:8238

My minified code works with breadthfirst layout fine.

**Comment by clemsos** [comment]
Same error here using Meteor

**Comment by maxkfranz** [comment]
The issue is that Foograph dependency isn't good.  It is one object, yet it makes references to itself as if it were a separate object / global.  It has several prototypes jammed into one object.

Foograph is an old lib, and I didn't write it.  Making it global seems to fix the issue, as global variable names can not be minified.

It would be nice if it didn't have to be a global, but I have lots of higher priority things to do than refactor Foograph.
