### ISSUE TITLE
stop layout

### ISSUE THREAD

**Issue by Marianna1989** [cytoscape/cytoscape.js-spread#10]
I've created a menu where the user can choose between different layouts. If a layout is selected the others are stopped. I noticed that spread layout continues in background and layout.stop() has no effect. How can I stop the layout?
Thank you

**Comment by maxkfranz** [comment]
Since there are two layouts proper that this layout runs, have you handled both of them?

If you have suggestions to make the extension more streamlined for this case, you're welcome to discuss that further here or to open a pull request with suggested changes.
