### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src ..."

### ISSUE THREAD

**Issue by kchima** [cytoscape/cytoscape.js-spread#11]
I was eager to use spread, as it was the only way I could determine to roughly fill a dynamic viewport with many cytoscape layouts, and the demos are impressive. However, and forgive me if I've misunderstood the situation, but it seems to trigger our Content Security Policy with an unsafe-eval. We cannot change our CSP, so is there a way to disable the webworkers, or another way to avoid this unsafe-eval? I assume it is happening in [weaver](https://github.com/maxkfranz/weaver), but I am not sure.

`57330cf8-609e-4335-b9b2-021ec506c2fb:1 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src ....".

    at _ref_ (57330cf8-609e-4335-b9b2-021ec506c2fb:1:32)
    at 57330cf8-609e-4335-b9b2-021ec506c2fb:1529:17
    at 57330cf8-609e-4335-b9b2-021ec506c2fb:1714:7
    at 57330cf8-609e-4335-b9b2-021ec506c2fb:1716:4
_ref_ @ 57330cf8-609e-4335-b9b2-021ec506c2fb:1
(anonymous) @ 57330cf8-609e-4335-b9b2-021ec506c2fb:1529
(anonymous) @ 57330cf8-609e-4335-b9b2-021ec506c2fb:1714
(anonymous) @ 57330cf8-609e-4335-b9b2-021ec506c2fb:1716
28Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received`

It seems to happen at the top of this block:

`function _ref_(o){ return eval(o); };
function broadcast(m){ return message(m); };
function message(m){ postMessage(m); };
function listen(fn){
  self.addEventListener("message", function(m){ 
    if( typeof m === "object" && (m.data.$$eval || m.data === "$$start") ){
    } else { 
      fn( m.data );
    }
  });
};
self.addEventListener("message", function(m){  if( m.data.$$eval ){ eval( m.data.$$eval ); }  });
function resolve(v){ postMessage({ $$resolve: v }); };
function reject(v){ postMessage({ $$reject: v }); };
function Voronoi() {
    this.vertices = null;`

**Comment by maxkfranz** [comment]
The web worker / weaver stuff could be removed.  You're welcome to put up a PR, and it can get merged into the official release on npm.
