### ISSUE TITLE
Uncaught Error: Cannot find module 'weaverjs'

### ISSUE THREAD

**Issue by ling1726** [cytoscape/cytoscape.js-spread#5]
Hello,

I recently updated to 2.0.0, I am getting this error in the browser when running cytoscape. I am on cytoscape 3.2.7

**Comment by sfbrunner** [comment]
Same problem and error here. Any help available? Thanks!

**Comment by maxkfranz** [comment]
Use cytoscape-spread@3 and cytoscape@3
