### ISSUE TITLE
The boundingBox has no effect

### ISSUE THREAD

**Issue by taurenshaman** [cytoscape/cytoscape.js-spread#6]
**Scenario**
switch layout in selected elements.  
I tested breadthfirst/circle/concentric/cose/grid/random and spread, only spread refreshed the layout of whole graph.

**Bug**
It looks like that the boundingBox option is not working.

**Code**
```
var elements = cy.$(':selected'); 
var layout = cyLayoutOptions[layoutName];
layout.boundingBox = elements.boundingBox();

var tmp = elements.layout(cyLayoutOptions[layoutName]);
tmp.run();
```

**Screenshot**
![spread-layout-boundingBox-not-work](https://user-images.githubusercontent.com/1308706/61266369-27868000-a7c6-11e9-80da-18be071f9dd6.gif)

**Comment by maxkfranz** [comment]
Refer to the readme re. layout phases.
