### ISSUE TITLE
Enable subgraph layout

### ISSUE THREAD

**Issue by michaelhappycheng** [cytoscape/cytoscape.js-spread#7]
I would like to suggest spread to enable subgraph layout mentioned [here](https://js.cytoscape.org/#layouts) by replacing nodes and edges [definition](https://github.com/cytoscape/cytoscape.js-spread/blob/master/src/layout.js#L41) with 

```
  const nodes = options.eles.nodes();
  const edges = options.eles.edges();
```
thank you.

**Comment by maxkfranz** [comment]
That sounds like a good idea.  If you’d like to propose a change like that, you’re welcome to create a pull request.
